config/routes.rb
Rails.application.routes.draw do
	require 'resque/server'
	mount Resque::Server, at: '/jobs'

	resources :dishes
	resources :menus
	resources :menu_items
	resources :menu_pages

	match 'json_export' => 'reports#index', as: :json_export, via: :get
	match 'download_report' => 'reports#download_report', as: :download_report, via: :post
	
  root to: 'home#index'
end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :menu_pages
	has_many :menu_items, through: :menu_pages

	# I temporarily removed the validation for the purpose of uploading the given CSV records
	# Required columns/fields are to be confirmed with the Client in future development.
	validates_presence_of :name, :sponsor, :event, :venue, :place

	scope :by_place, -> (place) { where("place LIKE ? || location LIKE ?", "%#{place}%", "%#{place}%")}
	scope :by_date, -> (from, to) { where("DATE(date) BETWEEN ? AND ?", from, to) }
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def create
    if params[:file].size > 5000000 #5 MB
      flash[:error] = 'Sorry, File size should not be more than 5MB!'
      redirect_to new_menu_item_url
    else
      begin
        csv_file = params[:file]
        upload_csv_file(csv_file) # see application_controller
        ImportCsvJob.perform_later(csv_file.original_filename, 'menu')
        
        flash[:notice] = "Menu CSV was successfully uploaded and will be saved in background."
        redirect_to menus_url
      rescue => error
        flash[:error] = "Failed to upload CSV File! Error: #{error.message}"
        render :new
      end
    end
  end
private  
  def sort_column
    Menu.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end 
end
# Only used for clearing table in development.
# ActiveRecord::Base.connection.execute("TRUNCATE menus")

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menus/index.html.erb
<div class="page-header">
  <%= link_to new_menu_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-upload"></span>
    Upload CSV
  <% end %>

  <h1>Listing All Menus</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
        <th><%= sortable "name" %></th>
        <th><%= sortable "sponsor" %></th>
        <th><%= sortable "event" %></th>
        <th><%= sortable "venue" %></th>
        <th>Place</th>
        <th>Description</th>
        <th>Occasion</th>
        <th>Notes</th>
        <th>Call#</th>
        <th>Keywords</th>
        <th>Language</th>
        <th><%= sortable "date" %></th>
        <th>Location</th>
        <th>Currency</th>
        <th>Status</th>
        <th>Page#</th>
        <th>Dish#</th>
      </tr>
    </thead>
    <tbody>
    	<% @menus.each do |menu| %>
	    	<tr>
	        <td><%= menu.name %></td>
	        <td><%= menu.sponsor %></td>
	        <td><%= link_to menu.event, menu_path(menu) %></td>
	        <td><%= link_to menu.venue, menu_path(menu) %></td>
	        <td><%= menu.place %></td>
	        <td><%= menu.physical_description %></td>
	        <td><%= menu.occasion %></td>
	        <td><%= menu.notes %></td>
          <td><%= menu.call_number %></td>
          <td><%= menu.keywords %></td>
          <td><%= menu.language %></td>
          <td><%= menu.date %></td>
          <td><%= menu.location %> (<%= menu.location_type %>)</td>
          <td><%= menu.currency %> (<%= menu.currency_symbol%>)</td>
          <td><%= menu.status %></td>
          <td><%= menu.page_count %></td>
          <td><%= menu.dish_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pull-right">
  <%= will_paginate @menus, renderer: BootstrapPagination::Rails %>
</div>

app/views/menus/new.html.erb
<div class="page-header">
  <h1>Upload Menu Record</h1>
</div>

<%= render partial: '/partials/upload_form', locals: {upload_path: menus_path} %>

app/views/menus/show.html.erb
<div class="page-header">
  <%= link_to menus_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-list"></span>
    Menu List
  <% end %>

  <h1>Menu Info</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Name</th>
        <th>Sponsor</th>
        <th>Event</th>
        <th>Venue</th>
        <th>Place</th>
        <th>Description</th>
        <th>Occasion</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
    	<tr>
        <td><%= @menu.name %></td>
        <td><%= @menu.sponsor %></td>
        <td><%= @menu.event %></td>
        <td><%= @menu.venue %></td>
        <td><%= @menu.place %></td>
        <td><%= @menu.physical_description %></td>
        <td><%= @menu.occasion %></td>
        <td><%= @menu.notes %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Call#</th>
        <th>Keywords</th>
        <th>Language</th>
        <th>Date</th>
        <th>Location</th>
        <th>Currency</th>
        <th>Status</th>
        <th>Page#</th>
        <th>Dish#</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @menu.call_number %></td>
        <td><%= @menu.keywords %></td>
        <td><%= @menu.language %></td>
        <td><%= @menu.date %></td>
        <td><%= @menu.location %> (<%= @menu.location_type %>)</td>
        <td><%= @menu.currency %> (<%= @menu.currency_symbol%>)</td>
        <td><%= @menu.status %></td>
        <td><%= @menu.page_count %></td>
        <td><%= @menu.dish_count %></td>
      </tr>
    </tbody>
  </table>
</div>