config/routes.rb
Rails.application.routes.draw do
	require 'resque/server'
	mount Resque::Server, at: '/jobs'

	resources :dishes
	resources :menus
	resources :menu_items
	resources :menu_pages

	match 'json_export' => 'reports#index', as: :json_export, via: :get
	match 'download_report' => 'reports#download_report', as: :download_report, via: :post
	
  root to: 'home#index'
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
	# If you remove the optional: true, it will automatically requires the id
	# I added optional since records show that is not required.
	
	belongs_to :dish, optional: true
	belongs_to :menu, optional: true
	belongs_to :menu_page, optional: true

	# I temporarily removed the validation for the purpose of uploading the given CSV records
	# Required columns/fields are to be confirmed with the Client in future development.
	# validates_presence_of :price, :high_price
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end

  def create
    # Since MenuItem.csv need to be uploaded, I temporarily increase the allowed file size.
    if params[:file].size > 1200000000 #25000000 #25 MB
      flash[:error] = 'Sorry, File size should not be more than 25MB!'
      redirect_to new_menu_item_url
    else
    	begin
    		csv_file = params[:file]
        upload_csv_file(csv_file) # see application_controller
        ImportCsvJob.perform_later(csv_file.original_filename, 'menu_item')
    		
        flash[:notice] = "Menu Item CSV was successfully uploaded and will be saved in background."
        redirect_to menu_items_url
      rescue => error
      	flash[:error] = "Failed to upload CSV File! Error: #{error.message}"
        render :new
    	end
    end
  end
private  
  def sort_column
    MenuItem.column_names.include?(params[:sort]) ? params[:sort] : "menu_page_id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end 
end
# Only used for clearing table in development.
# ActiveRecord::Base.connection.execute("TRUNCATE menu_items")

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/views/menu_items/index.html.erb
<div class="page-header">
  <%= link_to new_menu_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-upload"></span>
    Upload CSV
  <% end %>

  <h1>Listing All Menu Items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th><%= sortable "menu_page_id" %></th>
        <th><%= sortable "price" %></th>
        <th><%= sortable "high_price" %></th>
        <th><%= sortable "dish_id" %></th>
        <th>xpos</th>
        <th>ypos</th>
      </tr>
    </thead>
    <tbody>
    	<% @menu_items.each do |item| %>
	    	<tr>
	        <td><%= item.menu_page.try(:page_number) %></td>
	        <td><%= number_to_currency(item.price) %></td>
	        <td><%= number_to_currency(item.high_price) %></td>
	        <td><%= item.dish.try(:name) %></td>
	        <td><%= item.xpos %></td>
	        <td><%= item.ypos %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pull-right">
  <%= will_paginate @menu_items, renderer: BootstrapPagination::Rails %>
</div>

app/views/menu_items/new.html.erb
<div class="page-header">
  <h1>Upload Menu-Item Record</h1>
</div>

<%= render partial: '/partials/upload_form', locals: {upload_path: menu_items_path} %>