config/routes.rb
Rails.application.routes.draw do
	require 'resque/server'
	mount Resque::Server, at: '/jobs'

	resources :dishes
	resources :menus
	resources :menu_items
	resources :menu_pages

	match 'json_export' => 'reports#index', as: :json_export, via: :get
	match 'download_report' => 'reports#download_report', as: :download_report, via: :post
	
  root to: 'home#index'
end

app/models/menu_page.rb
class MenuPage < ApplicationRecord
	belongs_to :menu, optional: true
	has_many :menu_items

	# I temporarily removed the validation for the purpose of uploading the given CSV records
	# Required columns/fields are to be confirmed with the Client in future development.
	# validates_presence_of :page_number
end

app/controllers/menu_pages_controller.rb
class MenuPagesController < ApplicationController
  def index
    @menu_pages = MenuPage.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end

  def create
    if params[:file].size > 5000000 #5 MB
      flash[:error] = 'Sorry, File size should not be more than 5MB!'
      redirect_to new_menu_item_url
    else
      begin
        csv_file = params[:file]
        upload_csv_file(csv_file) # see application_controller
        ImportCsvJob.perform_later(csv_file.original_filename, 'menu_page')
        
        flash[:notice] = "Menu Page CSV was successfully uploaded and will be saved in background."
        redirect_to menu_pages_url
      rescue => error
        flash[:error] = "Failed to upload CSV File! Error: #{error.message}"
        render :new
      end
    end
  end
private  
  def sort_column
    MenuPage.column_names.include?(params[:sort]) ? params[:sort] : "menu_id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end 
end
# Only used for clearing table in development.
# ActiveRecord::Base.connection.execute("TRUNCATE menu_pages")

app/helpers/menu_page_helper.rb
module MenuPageHelper
end

app/views/menu_pages/index.html.erb
<div class="page-header">
  <%= link_to new_menu_page_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-upload"></span>
    Upload CSV
  <% end %>

  <h1>Listing All Menu-Pages</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th><%= sortable "menu_id" %></th>
        <th><%= sortable "page_number" %></th>
        <th>Image ID</th>
        <th><%= sortable "full_height" %></th>
        <th><%= sortable "full_width" %></th>
        <th>UUID</th>
      </tr>
    </thead>
    <tbody>
    	<% @menu_pages.each do |page| %>
	    	<tr>
	        <td><%= page.menu.try(:name) %></td>
	        <td><%= page.page_number %></td>
	        <td><%= page.image_id %></td>
	        <td><%= page.full_height %></td>
	        <td><%= page.full_width %></td>
	        <td><%= page.uuid %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pull-right">
  <%= will_paginate @menu_pages, renderer: BootstrapPagination::Rails %>
</div>

app/views/menu_pages/new.html.erb
<div class="page-header">
  <h1>Upload Menu-Page Record</h1>
</div>

<%= render partial: '/partials/upload_form', locals: {upload_path: menu_pages_path} %>