config/routes.rb
Rails.application.routes.draw do
	require 'resque/server'
	mount Resque::Server, at: '/jobs'

	resources :dishes
	resources :menus
	resources :menu_items
	resources :menu_pages

	match 'json_export' => 'reports#index', as: :json_export, via: :get
	match 'download_report' => 'reports#download_report', as: :download_report, via: :post
	
  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Hivetec Exam</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <#%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %> -->
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Hivetec | Exam", "/", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Dishes", dishes_path %></li>
          <li><%= link_to "Menu", menus_path %></li>
          <li><%= link_to "Menu-Item", menu_items_path %></li>
          <li><%= link_to "Menu-Page", menu_pages_path %></li>
          <li><%= link_to "Json-Export", json_export_path %></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == 'notice' ? "success" : "danger" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <script type="text/javascript">
    $(function(){
      var flash = "<%= flash[:notice] %>";
      if(flash.length > 0){
        setTimeout(function(){
          location.reload();
        }, 3000);
      }
    });
  </script>
  <%= yield :custom_scripts %>
</body>
</html>